framework:
    messenger:
        failure_transport: failed

        transports:
            scheduler_hijri_holidays:
                dsn: 'doctrine://default?queue_name=scheduler_hijri_holidays'
                options:
                    auto_setup: true
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\UpdateHijriHolidaysMessage': scheduler_hijri_holidays

    scheduler:
        enabled: true

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
