version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prayer_time_app
        ports:
            - "8080:80"
        environment:
            APP_ENV: prod
            APP_SECRET: ${APP_SECRET:-changeme_secret_key_here}
        volumes:
            - ./var/cache:/var/www/html/var/cache
            - ./var/log:/var/www/html/var/log
        restart: unless-stopped
