version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prayer_time_app
        ports:
            - "80"
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - DATABASE_URL=postgresql://msoufi:3hNRxw9CdudnkdH5cN2c@symfony_postgres:5432/prayer_time_db?serverVersion=16&charset=utf8
            - MESSENGER_TRANSPORT_DSN=doctrine://default
        volumes:
            - ./var/log:/var/www/html/var/log
            - ./var/cache:/var/www/html/var/cache
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 5s
            retries: 3
        networks:
            - proxy_net
        restart: unless-stopped

networks:
    proxy_net:
        external: true
